import type { Metadata } from "next";
import { Inter, Instrument_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const instrument_sans = Instrument_Sans({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-instrument_sans",
});

export const metadata: Metadata = {
    title: "Devlinks",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} ${instrument_sans.variable}`}>
                {children}
            </body>
        </html>
    );
}
