import {
    GithubIcon,
    FrontendMentor,
    TwitterIcon,
    YoutubeIcon,
    FacebookIcon,
    CodepenIcon,
    CodewarsIcon,
    TwitchIcon,
    LinkedInIcon,
    GitlabIcon,
    FreecodecampIcon,
    HashnodeIcon,
    StackoverflowIcon,
    DevtoIcon,
} from "@/public/assets/svgs";

export const platformIcons: Record<string, JSX.Element> = {
    github: <GithubIcon className="fill-white" />,
    "frontend mentor": <FrontendMentor className="fill-grey" />,
    twitter: <TwitterIcon className="fill-white" />,
    linkedin: <LinkedInIcon className="fill-white" />,
    youtube: <YoutubeIcon className="fill-white" />,
    facebook: <FacebookIcon className="fill-white" />,
    twitch: <TwitchIcon className="fill-white" />,
    "dev.to": <DevtoIcon className="fill-grey" />,
    codewars: <CodewarsIcon className="fill-white" />,
    codepen: <CodepenIcon className="fill-white" />,
    freecodecamp: <FreecodecampIcon className="fill-white" />,
    gitlab: <GitlabIcon className="fill-white" />,
    hashnode: <HashnodeIcon className="fill-white" />,
    "stack overflow": <StackoverflowIcon className="fill-white" />,
};

export const platformBgcolor: Record<string, string> = {
    github: "#1A1A1A",
    "frontend mentor": "#FFF",
    twitter: "#43B7E9",
    linkedin: "#2D68FF",
    youtube: "#EE3939",
    facebook: "#2442AC",
    twitch: "#EE3FC8",
    "dev.to": "#333333",
    codewars: "#8A1A50",
    codepen: "#302267",
    freecodecamp: "#302267",
    gitlab: "#EB4925",
    hashnode: "#0330D1",
    "stack overflow": "#EC7100",
};
